version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - users
      - products
      - web
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - prodnet01
      - usernet01
      - webnet01

  users:
    build: ./users
    ports:
      - "5000:5000"
    container_name: users
    networks:
      - usernet01

  web:
    build: ./web
    restart: always
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - webnet01

  mongo:
    image: mongo:latest
    hostname: mongo-host
    networks:
      - usernet01
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    hostname: myhost
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=productdb
    ports:
      - "3306:3306"
    networks:
      - prodnet01

  products:
    build: ./products
    restart: always
    ports:
      - "8000:8000"
    networks:
      - prodnet01
    container_name: products
    depends_on:
      - mysql

networks:
  usernet01:
  prodnet01:
  webnet01: